title: Przykładowa Firma Sp. z o.o.
description: Strona firmowa z aktualnościami
baseurl: ""
url: "https://mknet73.github.io"

nav:
  - title: "Strona główna"
    url: /
  - title: "O nas"
    url: /about/
  - title: "Kontakt"
    url: /contact/
  - title: "Aktualności"
    url: /aktualnosci/

markdown: kramdown
permalink: /:collection/:title/
collections:
  aktualnosci:
    output: true
    permalink: /aktualnosci/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
