title: Przykładowa Firma Sp. z o.o.
description: Strona firmowa z aktualnościami
baseurl: "" # jeśli jest na github.io, zostaw puste
url: "https://mknet73.github.io"

nav:
  - title: "Strona główna"
    url: /
  - title: "O nas"
    url: /about/
  - title: "Aktualności"
    url: /aktualnosci/
  - title: "Dokumenty"
    url: /dokumenty/
  - title: "Kontakt"
    url: /contact/

markdown: markdown
permalink: /posts/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
