backend:
  name: github
  repo: mknet73/mknet73.github.io
  branch: main
  client_id: Ov23lie2y44KX6f4Vjo7
  client_secret: 0df0bcbd2fa25efa6098926e05b992af0587e0d0

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "news"
    label: "Aktualności"
    folder: "_posts/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Tytuł" }
      - { name: "date", label: "Data", widget: "datetime" }
      - { name: "body", label: "Treść", widget: "markdown" }
  - name: "documents"
    label: "Dokumenty"
    folder: "assets/documents"
    create: true
    fields:
      - { name: "title", label: "Nazwa dokumentu" }
      - { name: "file", label: "Plik", widget: "file" }
      - { name: "date", label: "Data", widget: "datetime" }
